version: '3'

services:
  laravel:
    build:
      context: ./laravel-example
      dockerfile: Dockerfile.prod
    image: diogo96/laravel-example
    container_name: laravel-example
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx-example
      dockerfile: Dockerfile.prod
    image: diogo96/nginx-example
    container_name: nginx-example
    networks:
      - laranet
    ports:
      - 8080:80
networks:
  laranet:
